-- Função que gera DDL completo de todas as tabelas públicas a partir do information_schema.
-- Usada pelo endpoint GET /api/admin/exportar-schema para download do esquema.

CREATE OR REPLACE FUNCTION public.exportar_schema_ddl()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_out     TEXT;
  r_tab     RECORD;
  r_col     RECORD;
  r_idx     RECORD;
  v_sep     TEXT;
  v_tipo    TEXT;
  v_pk_cols TEXT;
BEGIN
  v_out := '-- Esquema gerado em: ' || to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') || ' UTC'
        || E'\n-- Banco: ' || current_database()
        || E'\n\n';

  FOR r_tab IN
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    ORDER BY table_name
  LOOP
    v_out := v_out || 'CREATE TABLE IF NOT EXISTS ' || quote_ident(r_tab.table_name) || ' (' || E'\n';
    v_sep  := '';

    FOR r_col IN
      SELECT
        column_name, data_type, udt_name, is_nullable,
        column_default, character_maximum_length,
        numeric_precision, numeric_scale,
        is_identity, identity_generation
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = r_tab.table_name
      ORDER BY ordinal_position
    LOOP
      -- Resolve tipo
      v_tipo := CASE
        WHEN r_col.data_type = 'ARRAY' THEN
          CASE r_col.udt_name
            WHEN '_int2'    THEN 'SMALLINT[]'
            WHEN '_int4'    THEN 'INTEGER[]'
            WHEN '_int8'    THEN 'BIGINT[]'
            WHEN '_text'    THEN 'TEXT[]'
            WHEN '_varchar' THEN 'TEXT[]'
            WHEN '_uuid'    THEN 'UUID[]'
            WHEN '_bool'    THEN 'BOOLEAN[]'
            ELSE 'TEXT[]'
          END
        WHEN r_col.data_type = 'USER-DEFINED' THEN
          CASE r_col.udt_name
            WHEN 'uuid'   THEN 'UUID'
            WHEN 'citext' THEN 'CITEXT'
            ELSE r_col.udt_name
          END
        WHEN r_col.data_type = 'character varying' THEN
          CASE WHEN r_col.character_maximum_length IS NOT NULL
               THEN 'VARCHAR(' || r_col.character_maximum_length || ')'
               ELSE 'TEXT' END
        WHEN r_col.data_type = 'character' THEN
          'CHAR(' || COALESCE(r_col.character_maximum_length::TEXT, '1') || ')'
        WHEN r_col.data_type = 'numeric' THEN
          CASE WHEN r_col.numeric_precision IS NOT NULL
               THEN 'NUMERIC(' || r_col.numeric_precision || ',' || r_col.numeric_scale || ')'
               ELSE 'NUMERIC' END
        WHEN r_col.data_type = 'integer'                     THEN 'INTEGER'
        WHEN r_col.data_type = 'bigint'                      THEN 'BIGINT'
        WHEN r_col.data_type = 'smallint'                    THEN 'SMALLINT'
        WHEN r_col.data_type = 'boolean'                     THEN 'BOOLEAN'
        WHEN r_col.data_type = 'text'                        THEN 'TEXT'
        WHEN r_col.data_type = 'jsonb'                       THEN 'JSONB'
        WHEN r_col.data_type = 'json'                        THEN 'JSON'
        WHEN r_col.data_type = 'timestamp with time zone'    THEN 'TIMESTAMPTZ'
        WHEN r_col.data_type = 'timestamp without time zone' THEN 'TIMESTAMP'
        WHEN r_col.data_type = 'date'                        THEN 'DATE'
        WHEN r_col.data_type = 'double precision'            THEN 'DOUBLE PRECISION'
        WHEN r_col.data_type = 'real'                        THEN 'REAL'
        WHEN r_col.data_type = 'interval'                    THEN 'INTERVAL'
        ELSE upper(r_col.data_type)
      END;

      v_out := v_out || v_sep || '  ' || quote_ident(r_col.column_name) || ' ' || v_tipo;

      -- IDENTITY (migration 022+)
      IF r_col.is_identity = 'YES' THEN
        v_out := v_out || ' GENERATED ' || r_col.identity_generation || ' AS IDENTITY';

      -- SERIAL legado (nextval) → converte para IDENTITY BY DEFAULT
      ELSIF r_col.column_default IS NOT NULL
        AND r_col.column_default LIKE 'nextval(%'
        AND r_col.data_type IN ('integer', 'bigint', 'smallint')
      THEN
        v_out := v_out || ' GENERATED BY DEFAULT AS IDENTITY';

      -- DEFAULT normal
      ELSIF r_col.column_default IS NOT NULL THEN
        v_out := v_out || ' DEFAULT ' || r_col.column_default;
      END IF;

      -- NOT NULL (IDENTITY e SERIAL já são implicitamente NOT NULL)
      IF r_col.is_nullable = 'NO'
         AND r_col.is_identity = 'NO'
         AND NOT (
           COALESCE(r_col.column_default, '') LIKE 'nextval(%'
           AND r_col.data_type IN ('integer', 'bigint', 'smallint')
         )
      THEN
        v_out := v_out || ' NOT NULL';
      END IF;

      v_sep := ',' || E'\n';
    END LOOP;

    -- PRIMARY KEY
    SELECT string_agg(quote_ident(kcu.column_name), ', ' ORDER BY kcu.ordinal_position)
    INTO v_pk_cols
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON kcu.constraint_name = tc.constraint_name
     AND kcu.table_schema    = tc.table_schema
    WHERE tc.table_schema    = 'public'
      AND tc.table_name      = r_tab.table_name
      AND tc.constraint_type = 'PRIMARY KEY';

    IF v_pk_cols IS NOT NULL THEN
      v_out := v_out || ',' || E'\n' || '  PRIMARY KEY (' || v_pk_cols || ')';
    END IF;

    v_out := v_out || E'\n);\n\n';
  END LOOP;

  -- Índices (exclui PKs; UNIQUE constraints aparecem como CREATE UNIQUE INDEX)
  v_out := v_out || E'-- Indexes\n';
  FOR r_idx IN
    SELECT indexdef
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname  NOT LIKE '%_pkey'
    ORDER BY tablename, indexname
  LOOP
    v_out := v_out || r_idx.indexdef || E';\n';
  END LOOP;

  RETURN v_out;
END;
$$;

GRANT EXECUTE ON FUNCTION public.exportar_schema_ddl() TO service_role;
