-- 066 — skill_natureza.item passa a ser gerado pelo banco
--
-- As outras três tabelas de apoio de skill (skill_tipo, skill_categoria,
-- skill_tipo_dano) já têm sequence própria para `item`. skill_natureza ficou
-- sem nenhum default, então o backend calculava MAX(item)+1 na mão antes de
-- inserir — duas idas ao banco por inserção e duas criações simultâneas
-- escolhendo o mesmo número.
--
-- BY DEFAULT (e não ALWAYS) para que um INSERT que informe `item`
-- explicitamente continue funcionando, como acontece nas migrations de seed.

DO $$
DECLARE
  proximo_item INTEGER;
BEGIN
  -- Idempotente: não faz nada se a coluna já for identity.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'skill_natureza'
      AND column_name = 'item'
      AND is_identity = 'YES'
  ) THEN
    RAISE NOTICE 'skill_natureza.item já é identity — nada a fazer.';
    RETURN;
  END IF;

  ALTER TABLE skill_natureza ALTER COLUMN item ADD GENERATED BY DEFAULT AS IDENTITY;

  -- Continua de onde os dados param, contando inclusive os soft-deletados:
  -- o item deles ainda ocupa a chave primária.
  SELECT COALESCE(MAX(item), 0) + 1 INTO proximo_item FROM skill_natureza;
  EXECUTE format('ALTER TABLE skill_natureza ALTER COLUMN item RESTART WITH %s', proximo_item);

  RAISE NOTICE 'skill_natureza.item agora é identity, começando em %.', proximo_item;
END $$;
